### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by cytsunny** [IamPr377y/save-with-encoding#2]
I have tried using this package by` ctrl+shift+P`  and then `Save With Encoding: Select`. I choose my encoding. The encoding changed, but when I close and reopen my file, the encoding is still the previous one. It is just not saved.

**Comment by IamPr377y** [comment]
Atom doesn't autodetect encoding, it opens files with encoding specified in settings. If you didn't change it, it should be UTF-8. The file is saved with encoding you've chosen, it is just reopened with UTF-8. The solution to this would be to manually select encoding each time you open a file.
